# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 06:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogclass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclass',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogclass',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 4, 16, 6, 35, 53, 923750, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
